fn main() {
    // memory.x is auto-generated by embassy-stm32's "memory-x" feature.
    // The link.x / defmt.x linker scripts come from cortex-m-rt / defmt.

    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");

    // Test targets (tests/*.rs)
    // Same linker chain as bins: memory.x defines regions, link.x places sections.
    // embedded-test.x is auto-added by embedded-test-linker-script for test metadata.
    println!("cargo:rustc-link-arg-tests=--nmagic");
    println!("cargo:rustc-link-arg-tests=-Tmemory.x");
    println!("cargo:rustc-link-arg-tests=-Tlink.x");
    println!("cargo:rustc-link-arg-tests=-Tdefmt.x");
}
