fn main() {
    // memory.x is auto-generated by embassy-stm32's "memory-x" feature.
    // The link.x / defmt.x linker scripts come from cortex-m-rt / defmt.

    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");

    // Test targets (tests/*.rs)
    // link.x provides the memory layout via INCLUDE memory.x.
    // embedded-test.x provides test symbols (found via -L from embedded-test-linker-script).
    println!("cargo:rustc-link-arg-tests=--nmagic");
    println!("cargo:rustc-link-arg-tests=-Tlink.x");
    println!("cargo:rustc-link-arg-tests=-Tdefmt.x");
    println!("cargo:rustc-link-arg-tests=-Tembedded-test.x");
}
