fn main() {
    // memory.x is auto-generated by embassy-stm32's "memory-x" feature.
    // The link.x / defmt.x linker scripts come from cortex-m-rt / defmt.

    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");
}
