[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "rust-src"]
targets = [
    "thumbv6m-none-eabi",
    "thumbv7m-none-eabi",
    "thumbv7em-none-eabihf",
    "thumbv8m.main-none-eabihf",
]
