[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip {{ probe-chip }}"

# Alternatively, use `cargo embed` for RTT logging:
# runner = "probe-rs run --chip {{ probe-chip }}"

[build]
target = "{{ rust-target }}"

[env]
DEFMT_LOG = "info"
