[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip {{ probe-chip }}"
rustflags = ["-C", "linker=flip-link"]

# Alternative: flash via USB DFU (no debug probe, chip must be in DFU mode)
# runner = "cargo dfu"

[build]
target = "{{ rust-target }}"

[env]
DEFMT_LOG = "info"
